---
all:
  children:
    rhel_patch_targets:
      children:
        rhel_patch_pilot:
          hosts:
            demo-pilot-01:
              ansible_connection: local
              ansible_host: localhost
        rhel_patch_batch:
          hosts:
            demo-batch-01:
              ansible_connection: local
              ansible_host: localhost
            demo-batch-02:
              ansible_connection: local
              ansible_host: localhost
